name: "Java Quality Check"
description: "Reusable CI steps for Java Maven projects"

inputs:
  java-version:
    description: "Java version"
    required: false
    default: "17"

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}

    - name: Build with Maven
      run: mvn clean compile
      shell: bash

    - name: Run tests
      run: mvn test
      shell: bash
